sudo: required
services:
  - docker

before_install:
  - docker build -t baremaximum/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true baremaximum/react-test npm test -- --coverage

after_success:
  - docker build -t baremaximum/dumbfibonacci-client ./client
  - docker build -t baremaximum/dumbfibonacci-reverse-proxy ./nginx
  - docker build -t baremaximum/dumbfibonacci-server ./server
  - docker build -t baremaximum/dumbfibonacci-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push baremaximum/dumbfibonacci-client
  - docker push baremaximum/dumbfibonacci-reverse-proxy
  - docker push baremaximum/dumbfibonacci-server
  - docker push baremaximum/dumbfibonacci-worker


